### ISSUE TITLE
Support for netstd < 2.0

### ISSUE THREAD

**Issue by Tyrrrz** [manuelroemer/Nullable#5]
Just by glancing at the project I can't see any indication if this will work in a project that targets, for example, .NET Standard 1.1.
Does it? Are there technical limitations related to supporting lower versions?

**Comment by manuelroemer** [comment]
Hi, you are right, that's not documented anywhere - thank you for mentioning this! I'll update the README when I get to it.
It should be compatible with any .NET Standard >= 1.0 and any "legacy" .NET FW >= 2.0.

If you have any troubles with such a target framework, be sure to tell me so that we can resolve the issue.

**Comment by Tyrrrz** [comment]
Cool! I'll check it out and report back.

**Comment by Tyrrrz** [comment]
Looks like it works.
I noticed that you can't use `?` to denote types that might be null, but you can use `!` though. Is that expected?

**Comment by Tyrrrz** [comment]
Ugh, it looks like it's just ReSharper showing it up as an error.

**Comment by manuelroemer** [comment]
Glad to hear that it's working!

I can confirm that it's most likely ReSharper - the warnings work as expected in a `netstandard1.0` app:
![grafik](https://user-images.githubusercontent.com/30902964/68783901-029efe00-063c-11ea-8d55-5641d08fdecf.png)

It's surprising that it accepts `!` but not `?`. I would have expected this to be the other way around.

**Comment by Tyrrrz** [comment]
Cool, thanks for help :)
